/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import entidades.*;
import datos.CitaDAO;
import datos.HorarioDAO;
import logica.MedicoService;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmAgendaMedica extends javax.swing.JInternalFrame {
    
    private MedicoService medicoService = new MedicoService();
    private ArrayList<Medico> listaMedicos;
    
    public FrmAgendaMedica() {
        initComponents();
        cargarComboMedicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbMedico = new javax.swing.JComboBox<>();
        btnBuscarAgenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel2.setText("AGENDA MEDICA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Selecciona un medico :");

        cmbMedico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscarAgenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarAgenda.setText("Buscar");
        btnBuscarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAgendaActionPerformed(evt);
            }
        });

        tblHorarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dia", "Hora inicio", "Hora fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHorarios);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tabla de Horarios :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tabla de Citas :");

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Historia Clinica", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCitas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(cmbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnBuscarAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(0, 84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(166, 166, 166))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAgenda))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAgendaActionPerformed
        Medico medico = obtenerMedicoSeleccionado();
        if (medico == null) {
        JOptionPane.showMessageDialog(this, "Seleccione un medico.",
            "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }

        cargarTablaHorarios(medico);
        cargarTablaCitas(medico);
    }//GEN-LAST:event_btnBuscarAgendaActionPerformed
    
    private void cargarComboMedicos() {
    listaMedicos = medicoService.listarMedicos();
    DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
    for (Medico m : listaMedicos) {
        modelo.addElement(m.getCodigo() + " - " + m.getNombres() + " " + m.getApellidos());
    }
    cmbMedico.setModel(modelo);
    }
    
    private Medico obtenerMedicoSeleccionado() {
    int indice = cmbMedico.getSelectedIndex();
    if (indice >= 0) {
        return listaMedicos.get(indice);
    }
    return null;
    }
    
    private void cargarTablaHorarios(Medico medico) {
    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    modelo.addColumn("Dia");
    modelo.addColumn("Hora Inicio");
    modelo.addColumn("Hora Fin");

    ArrayList<HorarioMedico> horarios = HorarioDAO.listarHorariosPorMedico(medico);
    for (HorarioMedico h : horarios) {
        Object[] fila = {
            h.getDiaSemana(), h.getHoraInicio(), h.getHoraFin()
        };
        modelo.addRow(fila);
    }
    tblHorarios.setModel(modelo);
    }
    
    private void cargarTablaCitas(Medico medico) {
    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    modelo.addColumn("Codigo Cita");
    modelo.addColumn("Historia Clinica");
    modelo.addColumn("Fecha");
    modelo.addColumn("Hora");
    modelo.addColumn("Estado");

    ArrayList<Cita> todasLasCitas = CitaDAO.listarCitas();
    for (Cita c : todasLasCitas) {
        if (c.getMedico().getCodigo().equals(medico.getCodigo())) {
            Object[] fila = {
                c.getCodigo(), c.getNumeroHistoriaClinica(),
                c.getFecha(), c.getHora(), c.getEstado()
            };
            modelo.addRow(fila);
        }
    }
    tblCitas.setModel(modelo);
    }

    //PROBAR
    public static void main(String[] args) {
        javax.swing.JFrame frame = new javax.swing.JFrame("Prueba de Agenda Médica");
        javax.swing.JDesktopPane desktop = new javax.swing.JDesktopPane();
        FrmAgendaMedica internalFrame = new FrmAgendaMedica();
        
        frame.setSize(950, 680);
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(desktop);
        
        desktop.add(internalFrame);
        internalFrame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAgenda;
    private javax.swing.JComboBox<String> cmbMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCitas;
    private javax.swing.JTable tblHorarios;
    // End of variables declaration//GEN-END:variables
}
