/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import entidades.Paciente;
import entidades.Rol;
import entidades.Usuario;
import logica.composite.CategoriaMenu;
import logica.composite.ItemMenu;
import logica.composite.MenuBuilder;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author yordi
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    private Usuario usuarioActual;


    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        usuarioActual = new Usuario(1, "sdfsdf", "asdas", Rol.ADMINISTRADOR, true);

        armarMenuDinamico();
    }

    public FrmPrincipal(Usuario usuarioActual) {
        initComponents();

        this.usuarioActual = usuarioActual;

        armarMenuDinamico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    private void armarMenuDinamico(){
        JMenuBar barraPrincipal;

        barraPrincipal = MenuBuilder.crear()

                .agregarCategoria("Usuarios")
                    .agregarItem("Registrar Usuario", e -> {}, Rol.ADMINISTRADOR)
                    .agregarItem("Buscar Usuario", e -> {}, Rol.ADMINISTRADOR)
                    .agregarItem("Modificar Usuario", e -> {}, Rol.ADMINISTRADOR)
                    .agregarItem("Eliminar Usuario", e -> {}, Rol.ADMINISTRADOR)
                    .agregarItem("Listar Usuarios", e -> {}, Rol.ADMINISTRADOR)

                .agregarCategoria("Pacientes")
                    .agregarItem("Registrar Paciente", e -> {abrirInternalFrame(new FrmRegistroPaciente());}, Rol.ADMINISTRADOR, Rol.RECEPCIONISTA)
                    .agregarItem("Buscar Paciente", e -> {}, Rol.ADMINISTRADOR, Rol.RECEPCIONISTA)
                    .agregarItem("Editar Paciente", e -> {}, Rol.ADMINISTRADOR, Rol.RECEPCIONISTA)

                .build(usuarioActual.getRol());


        this.setJMenuBar(barraPrincipal);
    }

    public void abrirInternalFrame(JInternalFrame frame) {
        if (frame == null) return;

        if (frame.getParent() == null) {
            desktopPane.add(frame);
        }

        int x = (desktopPane.getWidth() - frame.getWidth()) / 2;
        int y = (desktopPane.getHeight() - frame.getHeight()) / 2;

        x = Math.max(0, x);
        y = Math.max(0, y);

        frame.setLocation(x, y);
        frame.setVisible(true);

        try {
            frame.setSelected(true);
            frame.toFront();
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    // End of variables declaration//GEN-END:variables
}
