/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import entidades.Rol;
import logica.composite.CategoriaMenu;
import logica.composite.ItemMenu;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author yordi
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        armarMenuDinamico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    private void armarMenuDinamico(){
        JMenuBar barraPrincipal = new JMenuBar();


        //CATEGORIA USUARIOS
        CategoriaMenu mnuUsuarios = new CategoriaMenu("Usuarios");

        ItemMenu mniRegistrarUsuario = new ItemMenu("Registrar Usuario", e -> {}, Rol.ADMINISTRADOR);
        ItemMenu mniBuscarUsuario = new ItemMenu("Buscar Usuario", e -> {}, Rol.ADMINISTRADOR);
        ItemMenu mniModificarUsuario = new ItemMenu("Modificar Usuario", e -> {}, Rol.ADMINISTRADOR);
        ItemMenu mniListarUsuarios = new ItemMenu("Listar Usuarios", e -> {}, Rol.ADMINISTRADOR);

        mnuUsuarios.agregarElementoHijo(mniRegistrarUsuario);










        JComponent menuResultante = mnuSeguridad.obtenerComponenteSwing(Rol.ADMINISTRADOR);

        if(menuResultante != null){
            barraPrincipal.add(menuResultante);
        }

        this.setJMenuBar(barraPrincipal);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
