/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author Cristopher
 */
public class IfrmComprobante extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmComprobante
     */
    public IfrmComprobante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPricipal = new javax.swing.JPanel();
        pnlBusqueda = new javax.swing.JPanel();
        IblTitulo3 = new javax.swing.JLabel();
        IblBuscarPor = new javax.swing.JLabel();
        cmbBuscarPor = new javax.swing.JComboBox<String>();
        IblBusqueda = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        IblTitulo = new javax.swing.JLabel();

        pnlPricipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlBusqueda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IblTitulo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IblTitulo3.setText("Buscar Comprobante");

        IblBuscarPor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblBuscarPor.setText("Busca por");

        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Número", "Paciente", "Fecha" }));

        IblBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IblBusqueda.setText("Valor");

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBusquedaLayout = new javax.swing.GroupLayout(pnlBusqueda);
        pnlBusqueda.setLayout(pnlBusquedaLayout);
        pnlBusquedaLayout.setHorizontalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(IblBuscarPor)
                .addGap(45, 45, 45)
                .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(IblBusqueda)
                .addGap(33, 33, 33)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(btnBuscar)
                .addGap(103, 103, 103))
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(IblTitulo3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBusquedaLayout.setVerticalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBusquedaLayout.createSequentialGroup()
                .addComponent(IblTitulo3)
                .addGap(24, 24, 24)
                .addGroup(pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblBuscarPor)
                    .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblBusqueda)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        IblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IblTitulo.setText("GESTION DE COMPROBANTES");

        javax.swing.GroupLayout pnlPricipalLayout = new javax.swing.GroupLayout(pnlPricipal);
        pnlPricipal.setLayout(pnlPricipalLayout);
        pnlPricipalLayout.setHorizontalGroup(
            pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPricipalLayout.createSequentialGroup()
                .addGroup(pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPricipalLayout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(IblTitulo))
                    .addGroup(pnlPricipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlPricipalLayout.setVerticalGroup(
            pnlPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPricipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(IblTitulo)
                .addGap(18, 18, 18)
                .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlPricipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblBuscarPor;
    private javax.swing.JLabel IblBusqueda;
    private javax.swing.JLabel IblTitulo;
    private javax.swing.JLabel IblTitulo3;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlPricipal;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
