/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import logica.FarmaciaLOG;
import entidades.EntregaMedicamento;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class IfrmDespachoFarmacia extends javax.swing.JInternalFrame {
    private final FarmaciaLOG farmaciaLOG;

    /**
     * Creates new form IfrmDespachoFarmacia
     */
    public IfrmDespachoFarmacia() {
        initComponents();
        this.farmaciaLOG = new FarmaciaLOG();
        
        this.setTitle("Despacho de Medicamentos - Farmacia");
        this.setClosable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
    }

    private void limpiarCampos() {
        txtIdAtencion.setText("");
        txtIdMedicamento.setText("");
        txtCantidad.setText("");
        txtIdAtencion.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblAtencion = new javax.swing.JLabel();
        txtIdAtencion = new javax.swing.JTextField();
        lblMedicamento = new javax.swing.JLabel();
        txtIdMedicamento = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnDespachar = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Despacho y Entrega de Medicamentos");

        lblAtencion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAtencion.setText("ID Atencion / Receta :");

        txtIdAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAtencionActionPerformed(evt);
            }
        });

        lblMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMedicamento.setText("ID Medicamento :");

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCantidad.setText("Cantidad :");

        btnDespachar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnDespachar.setText("Registrar Despacho");
        btnDespachar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespacharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedicamento)
                            .addComponent(lblAtencion)
                            .addComponent(lblCantidad))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdAtencion)
                            .addComponent(txtIdMedicamento)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addGap(54, 54, 54))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnDespachar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtencion)
                    .addComponent(txtIdAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicamento)
                    .addComponent(txtIdMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnDespachar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAtencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAtencionActionPerformed

    private void btnDespacharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespacharActionPerformed
        try {
            if (txtIdAtencion.getText().trim().isEmpty() || 
                txtIdMedicamento.getText().trim().isEmpty() || 
                txtCantidad.getText().trim().isEmpty()) {   
                JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int idAtencion = Integer.parseInt(txtIdAtencion.getText().trim());
            int idMedicamento = Integer.parseInt(txtIdMedicamento.getText().trim());
            int cantidad = Integer.parseInt(txtCantidad.getText().trim());

            String resultadoMsg = farmaciaLOG.procesarEntrega(idAtencion, idMedicamento, cantidad);

            JOptionPane.showMessageDialog(this, resultadoMsg, "Proceso de Despacho", JOptionPane.INFORMATION_MESSAGE);

            limpiarCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los ID y la Cantidad deben ser números enteros válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Validación / Error de Despacho", JOptionPane.WARNING_MESSAGE);
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnDespacharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDespachar;
    private javax.swing.JLabel lblAtencion;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdAtencion;
    private javax.swing.JTextField txtIdMedicamento;
    // End of variables declaration//GEN-END:variables
}
