/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import entidades.Rol;
import entidades.Usuario;
import logica.UsuarioLOG;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author yordi
 */
public class IfrmBuscarEditarEliminarUsuario extends javax.swing.JInternalFrame {

    private String usernameBuscar;
    private String username;
    private String password;
    private Rol rol;
    private boolean estado;
    private Usuario usuarioSeleccionado;

    public IfrmBuscarEditarEliminarUsuario() {
        initComponents();

        cargarRoles();

        limpiarCampos();
    }

    private boolean validarCampos() {
        if (txtUsername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo USERNAME esta vacio.", "Validacion", JOptionPane.WARNING_MESSAGE);
            txtUsername.requestFocus();
            return false;
        }

        if(chbxCambioPassword.isSelected()){
            if (txtPassword.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo CONTRASEÑA esta vacio.", "Validacion", JOptionPane.WARNING_MESSAGE);
                txtPassword.requestFocus();
                return false;
            }
        }

        if (cbxRol.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un ROL.", "Validacion", JOptionPane.WARNING_MESSAGE);
            cbxRol.requestFocus();
            return false;
        }
        if (cbxEstado.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un ESTADO.", "Validacion", JOptionPane.WARNING_MESSAGE);
            cbxEstado.requestFocus();
            return false;
        }
        return true;
    }

    private void limpiarCampos() {
        txtUsername.setText("");
        txtPassword.setText("");
        cbxRol.setSelectedIndex(-1);
        cbxEstado.setSelectedIndex(-1);
        chbxCambioPassword.setSelected(false);
        username = "";
        password = "";
        rol = null;
        estado = false;
        usuarioSeleccionado = null;
    }

    private void obtenerDatosFormulario() {
        username = txtUsername.getText().trim();
        if(chbxCambioPassword.isSelected()){
            password = txtPassword.getText().trim();
        } else {
            password = null;
        }
        rol = Rol.valueOf((String) cbxRol.getSelectedItem());
        String estadoStr = (String) cbxEstado.getSelectedItem();
        estado = estadoStr.equals("ACTIVO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsernameBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        chbxCambioPassword = new javax.swing.JCheckBox();
        btnSalir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Usuario");

        txtUsernameBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameBusquedaKeyReleased(evt);
            }
        });

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Rol", "Estado"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jLabel2.setText("USERNAME");

        jLabel3.setText("CONTRASEÑA");

        txtPassword.setEnabled(false);

        jLabel4.setText("ROL");

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("ESTADO");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        chbxCambioPassword.setText("Cambiar contraseña");
        chbxCambioPassword.addItemListener(this::chbxCambioPasswordItemStateChanged);

        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(txtUsernameBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbxCambioPassword)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(138, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(btnModificar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsernameBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbxCambioPassword)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(178, 178, 178))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbxCambioPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbxCambioPasswordItemStateChanged
        
        if(chbxCambioPassword.isSelected()){
            txtPassword.setEnabled(true);
        } else txtPassword.setEnabled(false);
        
    }//GEN-LAST:event_chbxCambioPasswordItemStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
        cargarDatosEnTabla();
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        
        obtenerUsuarioSeleccionado();
        
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void txtUsernameBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameBusquedaKeyReleased
        
       if(txtUsernameBusqueda.getText().isEmpty()){
           cargarDatosEnTabla();
           return;
       }

       cargarDatosEnTabla(txtUsernameBusqueda.getText());
                
    }//GEN-LAST:event_txtUsernameBusquedaKeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if(usuarioSeleccionado == null){
            JOptionPane.showMessageDialog(this, "Usuario no seleccionado");
            return;
        }

        if(JOptionPane.showConfirmDialog(this, "¿Seguro que desea modificar los datos?") != JOptionPane.YES_OPTION){
            return;
        }

        if(!validarCampos()) return;

        obtenerDatosFormulario();

        UsuarioLOG.actualizarUsuario(usuarioSeleccionado.getIdUsuario(), username, password, rol, estado);

        limpiarCampos();

        cargarDatosEnTabla(txtUsernameBusqueda.getText());
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cargarRoles() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Rol rol : Rol.values()) {
            model.addElement(rol.name());
        }
        cbxRol.setModel(model);
    }

    private void cargarDatosEnTabla(String palabra){
        if(palabra.isEmpty() || palabra.equals("")) cargarDatosEnTabla();

        String[] columnas = {"USERNAME", "ROL", "ESTADO"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        ArrayList<Usuario> listaUsuarios = UsuarioLOG.listarUsuarios(palabra);

        for(Usuario u : listaUsuarios){
            Object[] fila = new Object[]{
                    u.getUsername(),
                    u.getRol().name(),
                    u.isEstado() ? "ACTIVO" : "INACTIVO"
            };

            modelo.addRow(fila);
        }

        tblUsuarios.setModel(modelo);
    }

    private void cargarDatosEnTabla(){
        String[] columnas = {"USERNAME", "ROL", "ESTADO"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        ArrayList<Usuario> listaUsuarios = UsuarioLOG.listarUsuarios();

        for(Usuario u : listaUsuarios){
            Object[] fila = new Object[]{
                    u.getUsername(),
                    u.getRol().name(),
                    u.isEstado() ? "ACTIVO" : "INACTIVO"
            };

            modelo.addRow(fila);
        }

        tblUsuarios.setModel(modelo);
    }

    private void obtenerUsuarioSeleccionado(){
        int filaSeleccionada = tblUsuarios.getSelectedRow();

        if(filaSeleccionada == -1) {
            limpiarCampos();
            return;
        }

        int fila = tblUsuarios.convertRowIndexToModel(filaSeleccionada);
        String usernameseleccionado = tblUsuarios.getModel().getValueAt(fila, 0).toString();

        usuarioSeleccionado = UsuarioLOG.buscarUsuario(usernameseleccionado);

        mostrarDatosUsuarioSeleccionado();
    }

    private void mostrarDatosUsuarioSeleccionado(){
        txtUsername.setText(usuarioSeleccionado.getUsername());
        cbxRol.setSelectedItem(usuarioSeleccionado.getRol().name());
        cbxEstado.setSelectedItem(usuarioSeleccionado.isEstado() ? "ACTIVO" : "INACTIVO");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JCheckBox chbxCambioPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsernameBusqueda;
    // End of variables declaration//GEN-END:variables
}
